from classes import *

pessoa = Pessoa ("PyTaOn", 4, 15)
pessoa.comer("maçã")
pessoa.comer("Melão")
pessoa.dormir()
pessoa.falar("oi")
pessoa.parardecomer()
pessoa.parardecomer()
pessoa.dormir()
pessoa.dormir()
pessoa.falar("oi")
pessoa.comer("Biscoito")
pessoa.acordar()
pessoa.acordar()
pessoa.falar("oi")
pessoa.dormir()
pessoa.comer("Milho")
pessoa.parardefalar()
pessoa.parardefalar()